### ISSUE TITLE
Should format tables more closely to existing TCG docs

### ISSUE THREAD

**Issue by jhand2** [TrustedComputingGroup/pandoc#33]
Currently tables render as borderless with alternating column colors. We should consider changing to a more traditional format which matches existing docs. This also includes how table headers are rendered.

Current rendering
![Current rendering](https://user-images.githubusercontent.com/11011105/208530988-acc704c1-f42f-45ac-9479-1dcdc8296ca6.png)

Example desired rendering
![Screen Shot 2022-12-19 at 1 51 36 PM](https://user-images.githubusercontent.com/11011105/208531138-745b0be7-e214-4054-bc4d-eff1c1c1ea19.png)

**Comment by chrisfenner** [comment]
The challenge on this one is to support styling tables with grids while retaining support for colspan/rowspan. There is an experimental build flag for our scripts called `--table_rules`, and it barfs if you have any colspan/rowspan tables in your document.

Leaving this open as if we could develop the filter to make this work with rowspans and colspans, it'd be spectacular. For now I am going to try to convince TCG to permit the "LaTeX style" tables, that look like this:

![image](https://github.com/TrustedComputingGroup/pandoc/assets/61842497/b27fdc52-db75-4bae-b0e2-dd9960df2e17)

**Comment by chrisfenner** [comment]
The latex package [tabularray](https://ctan.mirrors.hoobly.com/macros/latex/contrib/tabularray/tabularray.pdf) might be able to help us. I think we are close to needing to write our own pandoc filter that takes the internal Pandoc AST table and just writes out the longtblr invocations. Solutions I've found online based on patching longtable aren't working so far.

**Comment by jhand2** [comment]
fwiw, as long as the various involved WGs are fine with the updated format, I don't feel very strongly about this.

**Comment by chrisfenner** [comment]
Same. But TC asked for it. There are some tables in TCG specs where not having a horizontal rule makes it hard to correlate values between columns.

**Comment by chrisfenner** [comment]
Fixed in #103
