### ISSUE TITLE
Guidance for table colspan (and general guidance)

### ISSUE THREAD

**Issue by jhand2** [TrustedComputingGroup/pandoc#35]
Colspan (a row which spans multiple columns) is not possible in markdown tables.

![Screen Shot 2022-12-19 at 1 57 17 PM](https://user-images.githubusercontent.com/11011105/208531971-90be9c2d-b1a3-4b25-a710-0c3618d95a9f.png)

As an alternative, it is possible to embed HTML in your markdown doc and use HTML attributes to achieve this. Is there any guidance on how markdown docs should be authored (i.e. features you should/shouldn't use)?

As a backlog item, we should consider general guidance on how TCG docs should be authored (best practices) to achieve certain desired formatting. Maybe that should go in the [markdown](https://github.com/TrustedComputingGroup/markdown) repo though

**Comment by chrisfenner** [comment]
Latest guide covers how to do this
